### ISSUE TITLE
如果发图片报错typeerror的可以试试

### ISSUE THREAD

**Issue by azmiao** [A-kirami/whattoeat#1]
将这一块改成这样，适配cq码图片更新后的样子：
（这样还能在处理多图片的时候更加清楚明了）
try:
        foodname = ' '.join(map(str, [
            R.img(f'foods/{food_name}.jpg').cqcode,
        ]))
        to_eat += f'\n{foodname}'

**Comment by A-kirami** [comment]
感谢反馈，已修改
