### ISSUE TITLE
请问，转换CQ码出现错误是怎么回事？

### ISSUE THREAD

**Issue by Meitsuki233** [A-kirami/whattoeat#11]
![DM5VBHA7@$1XWVP %I9$VH6](https://user-images.githubusercontent.com/96688883/147410351-d41b09f5-44d1-4dc4-a15d-8c7c2aa7f935.png)
![3E8QA1}0%BAM9HEH(FRR8X0](https://user-images.githubusercontent.com/96688883/147410358-a4c62889-678e-457f-ac67-f9bfe6be8316.png)
这和路径有关系吗？

**Comment by A-kirami** [comment]
file not found
翻译：未找到文件
