### ISSUE TITLE
插件运行异常 CQEvent 没有match参数 使用HoshinoBot v2原版

### ISSUE THREAD

**Issue by elk-alter** [A-kirami/whattoeat#2]
![image](https://user-images.githubusercontent.com/30097656/116977672-4cc6e400-acf5-11eb-85e4-3aee5625ac3e.png)

报错信息如上

error at
whattoeat.py line 45

**Comment by A-kirami** [comment]
gocq版本是多少？0.39和1.0 beta3是实测无问题的
如果更换版本也无法解决该问题的话
请将报错这行的ev.match修改为ev['match']
看看是否能正常运行

**Comment by elk-alter** [comment]
go-cqhttp版本为
**v0.9.40-fix5**

将`ev.match`修改为`ev['match']`
可以正常运行

~~猜测可能与go-cqhttp版本有关~~
