### ISSUE TITLE
插件运行异常 素材已经放在img中，提示引用变量出错

### ISSUE THREAD

**Issue by plumephoenix** [A-kirami/whattoeat#3]
![图片](https://user-images.githubusercontent.com/83998495/117754996-02da8280-b24e-11eb-9975-4fcc500c6bab.png)

**Comment by A-kirami** [comment]
上方有错误提示：目录下未找到食谱
请检查是否有将foods.json放置在whattoeat.py同目录下
如果没有的，请放置在正确的位置后重启重新尝试能否正常使用

**Comment by plumephoenix** [comment]
> 
> 
> 上方有错误提示：目录下未找到食谱
> 请检查是否有将foods.json放置在whattoeat.py同目录下
> 如果没有的，请放置在正确的位置后重启重新尝试能否正常使用

foods.json是和whattoeat.py在同目录下的
![图片](https://user-images.githubusercontent.com/83998495/117812010-d34e6900-b293-11eb-812b-fb05dc632437.png)
而且不管json在不在，报的错是一样的

**Comment by A-kirami** [comment]
看了一下，你的文件夹名不正确，删除后面的-master就可以了

**Comment by plumephoenix** [comment]
> 
> 
> 看了一下，你的文件夹名不正确，删除后面的-master就可以了

谢谢明见佬，可以了，麻烦你解答了
