### ISSUE TITLE
大佬，为什么我打开就报错？？？

### ISSUE THREAD

**Issue by water-moon-flower** [A-kirami/whattoeat#6]
![QQ浏览器截图20210617195735](https://user-images.githubusercontent.com/85171753/122396123-42f9f700-cfaa-11eb-92d2-3ec1443cd626.png)

把文件夹放在 modules里放了，在config也放上了名字，怎么打开就报错呢？
![image](https://user-images.githubusercontent.com/85171753/122396307-72106880-cfaa-11eb-955b-72c327d58190.png)
对了，我看别人的用一个foods.josn，我下载这个为什么没有呢？？？需要自己建一个吗？求大佬解答！！

**Comment by A-kirami** [comment]
foods.josn已经在上次更新移除掉了，现在不需要foods.josn了
报错是缺少库（其实复制最底下那行百度就行（小声
在命令行输入
pip install filetype
安装完成后就可以了
